### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

#why numpy made

as python data types were slow ,so created new data types numpy array in python

### Creating Numpy Arrays

In [2]:
# np.array
import numpy as np

a = np.array([1,2,3])
print(a)
#a--vector

[1 2 3]


In [ ]:
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D
b = np.array([[1,2,3],[4,5,6]])
print(b)
#b--matrix

[[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
#c--tensor

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#if want custom data type in numpy array
# dtype
np.array([1,2,3],dtype=float)
#dtype can be bool ,complex etc.

array([1., 2., 3.])

In [ ]:
# np.arange
#works as a range to make array
np.arange(1,11,2)
#(rows ,columns)

array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(16).reshape(2,2,2,2)
#used to change shape of matrix

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# np.ones and np.zeros
#create array of each item as 1 or 0
#usecase -- create an array in neural networks when needed to create initialization of a number of networks
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
#initialize numpy array with random number in range(a,b)
np.random.random((3,4))

array([[0.1023547 , 0.17344651, 0.22279617, 0.15527941],
       [0.4462458 , 0.90465706, 0.50613937, 0.75082762],
       [0.53578683, 0.06970073, 0.1588361 , 0.02326523]])

In [ ]:
# np.linspace
#linearly space with range
#generate values each at the same space
#(startnum,endnum,total numbers)
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
#generate identity matrix with rows,column = (a)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# ndim
#to find number of dimensions
a2.ndim

2

In [ ]:
# shape
print(a3.shape)
#tell shape of numpyarray
#(number of array , number of row in each array ,no. of column in each array)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# size
#tell total number of items in an array
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# itemsize
#total size of array occupying
#int32--4 byte , int64-- 8 byte
a3.itemsize

8

In [ ]:
# dtype
#tell data type of numarray
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


### Changing Datatype

In [ ]:
# astype
#change the data type of an numpy array
#use-- agar kahi age store krni hai to float ki jgh int use krnenge bettter memory management ke liye
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
# scalar operations
#applies operation on each element
# arithmetic
a1 / 2
#any mathematical +,-,*,**,%,/,//

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
# relational
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [6]:
# vector operations-- 2 vectors pr combine operation

# arithmetic
(a1 ** a2)/a2

array([[ 0.00000000e+00,  7.69230769e-02,  1.17028571e+03,
         9.56593800e+05],
       [ 2.68435456e+08,  4.48787914e+10,  5.64221981e+12,
         5.99941852e+14],
       [ 5.76460752e+16, -6.00702529e+16,  8.47596386e+16,
         2.97355361e+17]])

### Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
#GENERATES RANDOM NO. BW 1 AND 100
a1

array([[43., 28., 71.],
       [27., 93., 36.],
       [31., 18.,  7.]])

In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.prod(a1,axis=0)#FIND PRODUCT OF COLUMNWISE ELEMENTS


array([35991., 46872., 17892.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)


array([317.55555556, 854.        ,  96.22222222])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

#CONDITION FOR DOT PRODUCT IN  M*N AND A*B , N SHOULD BE EQUAL TO A

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[48.,  4.,  6.],
       [ 3., 18., 82.]])

### Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[1,0]
#[ROW,COLUMN]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
#::JUMP AND RECEIVE
#A:: A+2 MEANS A+2 waala milega

### Iterating

In [ ]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
for i in np.nditer(a3):
  print(i)
#NDITER --- CONVERTS ANY D MATRIX INTO 1D

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


### Reshaping

In [ ]:
# reshape

In [ ]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
# ravel
#CONVERTS INTO 1D ARRAY
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

### Stacking

In [ ]:
# horizontal stacking
#MAKES     [][][]
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.hstack((a4,a5))


array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
#MAKES []
#      []
#      []
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.hsplit(a4,2)
#WORKS

In [ ]:
np.hsplit(a4,5)
#GIVES ERROR AS EQUAL DIVISION WORKS

ValueError: ignored

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
np.vsplit(a5,2)

ValueError: ignored